import { createApp } from "vue";
import { createI18n } from 'vue-i18n'
window.$ = window.jQuery = require('jquery');
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { dom, library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons';
import { far } from '@fortawesome/free-regular-svg-icons';
import { faLock, faEnvelope } from '@fortawesome/free-solid-svg-icons';
import router from './router'; // <---
import store from './store';
import VueCookies from 'vue-cookies';
import App from './App.vue';
import Loading from 'vue-loading-overlay';
import VueKonva from 'vue-konva';
import PrimeVue from 'primevue/config';
import DialogService from 'primevue/dialogservice';
//import adminlte scripts
import "../node_modules/admin-lte/dist/js/adminlte.min.js"
import "../node_modules/admin-lte/plugins/select2/js/select2.full.min.js"
import "../node_modules/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js"
import "../node_modules/admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"
import "../node_modules/admin-lte/plugins/daterangepicker/daterangepicker.js"
import "../node_modules/admin-lte/plugins/jquery-knob/jquery.knob.min.js"
import "../node_modules/admin-lte/plugins/sparklines/sparkline.js"
import "../node_modules/admin-lte/plugins/chart.js/Chart.min.js"
import "../node_modules/admin-lte/plugins/jquery/jquery.min.js"
import "../node_modules/admin-lte/plugins/jquery-ui/jquery-ui.min.js"
import "../node_modules/admin-lte/plugins/inputmask/jquery.inputmask.min.js"
import "../node_modules/admin-lte/plugins/bootstrap-switch/js/bootstrap-switch.min.js"
import "../node_modules/admin-lte/plugins/bs-stepper/js/bs-stepper.min.js"
import "../node_modules/admin-lte/plugins/dropzone/min/dropzone.min.js"
//import adminlte styles
import '../node_modules/admin-lte/dist/css/adminlte.min.css'
import "../node_modules/admin-lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css"
import "../node_modules/admin-lte/plugins/summernote/summernote-bs4.min.css"
import "../node_modules/admin-lte/plugins/daterangepicker/daterangepicker.css"
import "../node_modules/admin-lte/plugins/jqvmap/jqvmap.min.css"
import "../node_modules/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css"
import "../node_modules/admin-lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css"
import "../node_modules/admin-lte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css"
import "../node_modules/admin-lte/plugins/bs-stepper/css/bs-stepper.min.css"
import "../node_modules/admin-lte/plugins/dropzone/min/dropzone.min.css"
library.add(fas, fab, far, faLock, faEnvelope);
dom.watch()

const messages = {
    ru: {
        message: {
            welcome: 'Light Control Service',
			devices: 'Обзор устройств',
			deviceInfoHeader: 'Информация по выбранному устройству',
            project: 'Проект',
			log: 'Последние события',
			dashboard: 'Главная',
            deviceId: 'Адрес устройства',
            deviceType: 'Тип устройства',
            deviceStatus: 'Статус устройства',
            deviceManufacturer: 'Производитель',
            deviceModel: 'Модель',
            deviceLampHours: 'Кол-во часов',
            deviceIsIdentityOn: 'Показать лампу',
			deviceLabel: 'Метка',
			deviceDmxStartAddress: 'Начальный адрес DMX',
			deviceName: 'Наименование устройства',
			deviceParentId: 'Идентификатор родительского устройства',
			devicePortAddress: 'Порт',
			devicePortOutputStatus: 'Статус выходного порта',///////
			deviceFirmwareVersion: 'Версия прошивки',
			deviceOem: 'OEM',
			deviceUbeaVersion: 'Версия UBEA',
			deviceIsUbeaSupport:'Поддержка UBEA',
			deviceIsRdmSupported:'Поддержка RDM',
			deviceRomBoot:'Загрузка ПЗУ',
			deviceEstaCode:'EstaCode',
			deviceNodeReport:'NodeReport',
			deviceStyle:'Стиль',
			deviceMacAddress:'MAC address',
			deviceIpAddress:'IP address',
			deviceWebSupport:'Web support',
			deviceDhcpCapable: 'DHCP совместимость',
			deviceArtNet3Capable: 'Art-Net 3 совместимость',
			deviceBindIndex:'Bind index',
			deviceBindingAddress:'Binding address',
			deviceUid:'UId',
			deviceSoftwareVersionLabel:'Метка версии ПО',
			deviceFootprint:'Footprint',
			deviceSoftwareVersionId:'Идентификатор версии ПО',
			deviceBootSoftwareVersionLabel:'Метка версии загрузочного ПО',
			deviceBootSoftwareVersionId:'Идентификатор версии ПО загрузки',
			deviceModelId:'Идентификатор модели',
			devicePowerCycles:'Циклы питания',
			deviceHours:'Время работы устройства',
			deviceLampStrikes:'Зажигание лампы',
			deviceSensorsCount:'Количество сенсоров',
			deviceSensors:'Сенсоры',
			deviceSubDeviceCount:'Количество дочерних устройств',
			devicePanInvert:'Инвертирование панорамирования',
			deviceTiltInvert:'Инвертирование наклона',
			devicePanTiltSwap:'Переключение панорамирования/наклона',
			deviceLastSeen:'Последний опрос',
			deviceParameters:'Параметры',
			deviceOnOff:'1-авто включение / 0 авто выключение',
			deviceLogarithm:'1-Logarithm ON / 0 OFF',
			deviceDefaultBrCh1:'Default BrCh 1',
			deviceDefaultBrCh2:'Default BrCh 2',
			deviceDefaultBrCh3:'Default BrCh 3',
			deviceDefaultBrCh4:'Default BrCh 4',
			deviceSensorNumber:'Номер сенсора',
			deviceSensorDescription:'Описание сенсора',
			deviceSensorCurValue:'Текущее значение',
			deviceParametersDescription:'Наименование параметра',
			deviceParametersCurValue:'Значение параметра',
			deviceStatusLegend:'Легенда статусов:',
			deviceLoaded:'Загружен минимум 1 параметр',
			deviceNew:'Обнаружено',
			deviceLoading:'Ожидание загрузки параметров',
			deviceWarning:'Предупреждение',
			deviceLost:'Не отвечает',
			schedulerScenario:'Сценарий',
			schedulerDate:'Дата',
			schedulerStart:'Старт',
			schedulerRepeat:'Повторять',
			schedulerDuration:'Время работы сценария',
			weekDaysMonday:'Понедельник',
			weekDaysTuesday:'Вторник',
			weekDayWednesday:'Среда',
			weekDaysThursday:'Четверг',
			weekDaysFriday:'Пятница',
			weekDaysSaturday:'Суббота',
			weekDaysSunday:'Воскресенье',
			weekDaysWorkDays:'Будни',
			weekDayWeekendDays:'Выходные',
			weekDaysEveryday:'Каждый день',
			sunrize:'Восход',
			sunset: 'Закат',
			astronomicMinutes: 'минут',
			nowPlaying: 'Играет сейчас: ',
			nextPlaying: 'Следующая задача: ',
			isInProject: 'Есть в проекте',
			currentProject: 'Текущий проект: ',
			deviceReload: 'Обновить данные устройства',
			deviceScanFlagTrue: 'Устройства сканируются',
			deviceScanFlagfalse: 'Устройства не сканируются',
			deviceStartStopScanButton:'Старт/стоп сканирования устройств',
			projectUpload: 'Загрузить проект',
			projectRefreshButton: 'Обновить текущий проект',
			rendererStartStopAnim: 'Не показывать/Показывать анимацию',
			logRefresh: 'Обновить журнал',
			projectSchedulerFile: 'Текущий список задач',
			projectInfoTitle: 'Наименование проекта',
			projectInfoDate: 'Дата создания',
			projectInfoLastModify: 'Дата последнего редактирования',
			projectInfoAssembledBy:'Компания-исполнитель',
			projectInfoAssembledByCompany: 'Компания',
			projectInfoAssembledByName: 'Исполнитель',
			projectInfoAssembledByEmail: 'E-mail адрес',
			projectInfoPhone: 'Телефон',
			projectInfoAddress: 'Адрес',
			projectInfoCustomer:'Заказчик',
			projectInfoCustomerCompany: 'Компания',
			projectInfoCustomerName: 'Заказчик',
			projectInfoCustomerEmail: 'E-mail адрес',
			projectInfoCustomerPhone: 'Телефон',
			projectInfoCustomerAddress: 'Адрес',
			projectInfoDescription: 'Описание',
			projectInfoObjectAddress: 'Адрес объекта',
			projectManageSchedulerFiles: 'Управление файлами планировщика',
			delSchedulerFileAlert: 'Нельзя удалить текущий файл планировщика!',
			schedulerFileExists: 'Файл с таким именем уже существует!',
			schedulerFileNameEmpty: 'Введите название нового файла для планировщика!',
			logId: 'Идентификатор',
			logLevel: 'Уровень сообщения',
			logDeviceId: 'Номер устройства',
			logDescription: 'Описание события',
			logDateTime: 'Время события',
			schedulerStartStop: 'Стартовать/остановить все задачи',
			schedulerAddTask: 'Добавить задачу в планировщик',
			schedulerEditTask: 'Редактирование задачи планировщика',
			projectInfoHeader: 'Информация о проекте',
			projectProjectDevices: 'Устройства в проекте',
			projectProjectScheduler: 'Планировщик',
			projectProjectScenPlayer: 'Проигрывание сценариев',
			rendererFitToRasters:'Сбросить масштаб',
        }
    },
    en: {
        message: {
			welcome: 'Light Control Service',
			devices: 'Devices polling',
			deviceInfoHeader:'Device Info',
            project: 'Project',
			log: 'Last events',
			dashboard: 'Dashboard',
            deviceId: 'Device Id',
            deviceType: 'Device type',
            deviceStatus: 'Device status',
            deviceManufacturer: 'Manufacturer',
            deviceModel: 'Model',
            deviceLampHours: 'Lamp Hours',
            deviceIsIdentityOn: 'Identify Lamp',
			deviceLabel: 'Label',
			deviceDmxStartAddress: 'Start Address DMX',
			deviceName: 'Device name',
			deviceParentId:'Parent device Id',
			devicePortAddress: 'Port',
			devicePortOutputStatus: 'Output status',
			deviceFirmwareVersion: 'Firmware version',
			deviceOem: 'OEM',
			deviceUbeaVersion: 'UBEA version',
			deviceIsUbeaSupport:'Is UBEA supported',
			deviceIsRdmSupported:'Is RDM supported',
			deviceRomBoot:'ROM boot',
			deviceEstaCode:'EstaCode',
			deviceNodeReport:'NodeReport',
			deviceStyle:'Style',
			deviceMacAddress:'MAC address',
			deviceIpAddress:'IP address',
			deviceWebSupport:'Web support',
			deviceDhcpCapable: 'DHCP capable',
			deviceArtNet3Capable: 'Art-Net 3 capable',
			deviceBindIndex:'Bind index',
			deviceBindingAddress:'Binding address',
			deviceUid:'UId',
			deviceSoftwareVersionLabel:'Software version label',
			deviceFootprint:'Footprint',
			deviceSoftwareVersionId:'Software version Id',
			deviceBootSoftwareVersionLabel:'Boot software version label',
			deviceBootSoftwareVersionId:'Boot software version Id',
			deviceModelId:'Model Id',
			devicePowerCycles:'Power cycles',
			deviceHours:'Device hours',
			deviceLampStrikes:'Lamp strikes',
			deviceSensorsCount:'Sensors count',
			deviceSensors:'Sensors',
			deviceSubDeviceCount:'Sub device count',
			devicePanInvert:'Pan invert',
			deviceTiltInvert:'Tilt invert',
			devicePanTiltSwap:'Pan/Tilt swap',
			deviceLastSeen:'Last seen',
			deviceParameters:'Parameters',
			deviceOnOff:'1-Auto ON / 0 OFF',
			deviceLogarithm:'1-Logarithm ON / 0 OFF',
			deviceDefaultBrCh1:'Default BrCh 1',
			deviceDefaultBrCh2:'Default BrCh 2',
			deviceDefaultBrCh3:'Default BrCh 3',
			deviceDefaultBrCh4:'Default BrCh 4',
			deviceSensorNumber:'Sensor Number',
			deviceSensorDescription:'Sensor description',
			deviceSensorCurValue:'Present value',
			deviceParametersDescription:'Parameter name',
			deviceParametersCurValue:'Parameter value',
			deviceStatusLegend:'Device status legend',
			deviceLoaded:'Loaded',
			deviceNew:'New',
			deviceLoading:'Loading',
			deviceWarning:'Warning',
			deviceLost:'Lost',
			schedulerScenario:'Scenario',
			schedulerDate:'Date',
			schedulerStart:'Start',
			schedulerRepeat:'Repeat',
			schedulerDuration:'Duration',
			weekDaysMonday:'Monday',
			weekDaysTuesday:'Tuesday',
			weekDayWednesday:'Wednesday',
			weekDaysThursday:'Thursday',
			weekDaysFriday:'Friday',
			weekDaysSaturday:'Saturday',
			weekDaysSunday:'Sunday',
			weekDaysWorkDays:'Work days',
			weekDayWeekendDays:'Weekend days',
			weekDaysEveryday:'Everyday',
			sunrize:'Sunrize',
			sunset: 'Sunset',
			astronomicMinutes: 'minutes',
			nowPlaying: 'Playing now: ',
			nextPlaying: 'Next playing: ',
			isInProject: 'Exist In Project',
			currentProject: 'Current project: ',
			deviceReload: 'Refresh lamp data',
			deviceScanFlagTrue: 'Devices are scanning',
			deviceScanFlagfalse: 'Devices are not scanning',
			deviceStartStopScanButton: 'Start/stop device scanning',
			projectUpload: 'Upload project',
			projectRefreshButton: 'Refresh current project',
			rendererStartStopAnim: 'Start/stop animation',
			logRefresh: 'Refresh log table',
			projectSchedulerFile: 'Current list of tasks',
			projectInfoTitle: 'Project name',
			projectInfoDate: 'Creation date',
			projectInfoLastModify: 'Last modified',
			projectInfoAssembledBy: 'Assembled by',
			projectInfoAssembledByCompany: 'Company',
			projectInfoAssembledByName: 'Name',
			projectInfoAssembledByEmail: 'E-mail',
			projectInfoAssembledByPhone: 'Phone',
			projectInfoAssembledByAddress: 'Address',
			projectInfoCustomer: 'Customer',
			projectInfoCustomerCompany: 'Company',
			projectInfoCustomerName: 'Name',
			projectInfoCustomerEmail: 'E-mail',
			projectInfoCustomerPhone: 'Phone',
			projectInfoCustomerAddress: 'Address',
			projectInfoDescription: 'Description',
			projectInfoObjectAddress: 'Object address',
			projectManageSchedulerFiles: 'Manage scheduler files',
			delSchedulerFileAlert: 'You can\'t delete current scheduler file',
			schedulerFileExists: 'File with this filename is already existed!',
			schedulerFileNameEmpty: 'Enter new scheduler filename!',
			schedulerStartStop:'Start/Stop all tasks',
			logId: 'Id',
			logLevel: 'Message level',
			logDeviceId: 'Device id',
			logDescription: 'Description',
			logDateTime: 'Date and time of message',
			schedulerAddTask: 'Add task to scheduler',
			schedulerEditTask: 'Edit scheduler task',
			projectInfoHeader: 'Project Information',
			projectProjectDevices: 'Devices in project',
			projectProjectScheduler: 'Project scheduler',
			projectProjectScenPlayer: 'Scenario player',
			rendererFitToRasters: 'Set default scale',
        }
    },
}

const lang = createI18n({
    locale: 'ru',
    fallbackLocale: 'en',
    messages
});
const vueExemplar = createApp(App)/*.component('tabs', Tabs)
	.component('tab', Tab)*/;

vueExemplar.use(store).use(lang).use(PrimeVue).use(DialogService).use(Loading).use(VueKonva).use(router).use(VueCookies).mount("#app");